/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        ProjectController projectController = new ProjectController();
        
        Project project = new Project();

        /*
        //Teste de criação do novo projeto #create
        project.setName("Projeto teste 2");
        project.setDescription("Descrição do projeto 2 aqui");
        projectController.save(project);
        */
        
        /*
        //Teste de atualização do projeto #update
        project.setId(1);
        project.setName("Teste projeto atualizado.");
        project.setDescription("Atualizado descrição.");
        projectController.update(project);
        */
        
        /*
        //Total de projetos
        List<Project> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
        */
        
        /*
        //Deletar projeto #delete
        projectController.removeById(2);
        */
        
        
        TaskController taskController = new TaskController();
        Task task = new Task();
        
        /*
        //criar nova tarefa #create
        task.setIdProject(1);
        task.setName("Criar as telas da aplicação");
        task.setDescription("Devem ser criadas telas para os cadastros");
        task.setNotes("Sem notas");
        task.setCompleted(false);
        task.setDeadline(new Date());
        
        taskController.save(task);
        */
        
        /*
        //Atualizar tarefa #update
        task.setIdProject(1);
        task.setName("Alterar telas da aplicação");
        task.setDescription("Devem ser criadas telas para os cadastros");
        task.setNotes("Sem notas");
        task.setCompleted(false);
        task.setDeadline(new Date());
        task.setId(1);
        taskController.update(task);
        */
        
        /*
        //Buscar tarefas #select
        List<Task> tasks = taskController.getAll(1);
        System.out.println("Total de tarefas = " + tasks.size());
        */
        
        //Removendo a tarefa #delete
        //taskController.removeById(1);
        
    }
}
